[build]
  command = "pnpm run build"
  publish = ".next"
  functions = ".netlify/functions-internal"

# ✅ Enable Next.js runtime adapter
[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# ✅ Redirect all routes through Next.js
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/__render"
  status = 200