[build]
  command  = "pnpm build"
  publish  = ".next"
  functions = ".netlify/functions-internal"

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_NEXT_PLUGIN_SKIP = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Semua route dilewatkan ke renderer Next.js
[[redirects]]
  from = "/*"
  to   = "/.netlify/functions/__render"
  status = 200
